// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestSolution.SpecflowTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("My cool feature")]
    public partial class MyCoolFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Feature1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecflowTests", "My cool feature", "A short summary of the feature", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My cool test and stuff2")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public virtual void MyCoolTestAndStuff2()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My cool test and stuff2", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.When("I go to google.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then("I should be at gooble", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
 testRunner.When("I go to google.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.When("I go to google.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.When("I go to google.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
 testRunner.Then("I should be at gooble", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
 testRunner.Then("I should be at gooble", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
 testRunner.Then("I should be at gooble", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My cool test and stuff")]
        [NUnit.Framework.TestCaseAttribute("usernamea", "Bytes", "password1", "password1", "usernamea", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernameb", "Bytes", "password2", "password2", "usernameb", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamec", "Bytes", "password3", "password3", "usernamec", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamec", "Bytes", "password3", "password3", "usernamec", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamec", "Bytes", "password3", "password3", "usernamec", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamec", "Bytes", "password3", "password3", "usernamec", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamec", "Bytes", "password3", "password3", "usernamec", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamec", "Bytes", "password3", "password3", "usernamec", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamed", "Bytes", "password4", "password4", "usernamed", "Admin", null)]
        [NUnit.Framework.TestCaseAttribute("usernamee", "Bytes", "password5", "password5", "usernamee", "Admin", null)]
        public virtual void MyCoolTestAndStuff(string email, string organisation, string password, string passwordConfirmation, string username, string role, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("organisation", organisation);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("passwordConfirmation", passwordConfirmation);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("role", role);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My cool test and stuff", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 16
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 17
 testRunner.Then("I select username \'<epam>\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
